const fs=require('fs'),vm=require('vm');
const html=fs.readFileSync(__dirname+'/../index.html','utf8'),source=html.match(/<script>([\s\S]*?)<\/script>/)[1];
new vm.Script(source);
const elements=new Map();
function element(id){if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',style:{},insertAdjacentHTML(){},classList:{add(){},remove(){},toggle(){}},querySelector(){return {insertAdjacentHTML(){}}}});return elements.get(id)}
const context={document:{getElementById:element,querySelector:()=>({id:'home'}),querySelectorAll:()=>[]},window:{scrollTo(){}},setTimeout:()=>0,clearTimeout(){},navigator:{},console};
vm.createContext(context);vm.runInContext(source,context);
const tests=[
"function check(value,message){if(!value)throw Error(message)}",
"check(sizesFor(33).includes('M'),'Clothing');check(sizesFor(46).includes('32'),'Waist');check(sizesFor(41).includes('UK 8'),'Shoes');check(!sizesFor(8).length,'Electronics');",
"check(!pushCart(33,''),'Reject missing size');pushCart(33,'M');pushCart(33,'M');check(cart.length===1&&cart[0].qty===2,'Merge variants');pushCart(33,'L');check(cart.length===2,'Separate sizes');",
"changeQty(0,-1);check(cart[0].qty===1,'Quantity');editCartSize(1,'XL');check(cart[1].size==='XL','Edit size');removeCart(1);check(cart.length===1,'Remove');",
"toggleWish(33);check(wishlist.includes(33),'Save');toggleWish(33);check(!wishlist.includes(33),'Unsave');",
"cart=[];customizeBundle('Gym',sets.Gym,true);check($('bundleAdd').disabled,'Missing bundle sizes');bundleDraft.items[0].size='M';bundleDraft.items[2].size='32';updateBundleSummary();check(!$('bundleAdd').disabled,'Ready');confirmBundle();check(cart.length===4,'Bundle add');check(cartTotals().bundleDiscount===200,'Discount');removeCart(0);check(cartTotals().bundleDiscount===0,'Incomplete discount');",
"cart=[];customizeBundle('Gym',sets.Gym,true);bundleDraft.items.forEach(x=>x.included=false);updateBundleSummary();check($('bundleAdd').disabled,'Empty rejected');bundleDraft.items[1].included=true;confirmBundle();check(cart.length===1&&cart[0].id===13,'Partial add');check(!cartTotals().bundleDiscount,'Partial discount');",
"check(card(products[0]).includes('data-wish'),'Heart');check(products.filter(p=>p.rarelyReturned).length===8,'Return badges');"
];
vm.runInContext(tests.join('\n'),context);
for(const handler of html.split('<script>')[0].matchAll(/(?:onclick|onchange)="([^"]*)"/g))new vm.Script(handler[1]);
vm.runInContext("check(trendyPicks().length>0,'Default trendy picks');toggleInterest('Gaming');check(trendyPicks().every(p=>p.gtype),'Gaming personalization');toggleInterest('Bikes');check(trendyPicks().some(p=>p.c==='Garage'),'Combined interests');setTrendyBudget(300);check(trendyPicks().every(p=>p.p<300),'Budget filter');clearInterests();check(!followedInterests.length,'Reset interests');",context);
if(html.includes('id="rewards"')||html.includes('show("rewards")'))throw Error('Stale rewards navigation');
if(!html.includes('refer-card')||!html.includes('<video controls'))throw Error('Missing referrals or videos');
vm.runInContext("check(lensUrl(33).startsWith('https://lens.google.com/uploadbyurl?url='),'Lens URL');check(decodeURIComponent(lensUrl(33).split('?url=')[1])===products.find(p=>p.id===33).img,'Lens image encoding');check(lensUrl(-1)===null,'Missing image');const previousLook=activeLookIndex;lookPaused=false;lastLookChange=0;autoAdvanceLook();check(activeLookIndex===(previousLook+1)%shopLooks.length,'Auto advance');lookPaused=true;lastLookChange=0;const pausedLook=activeLookIndex;autoAdvanceLook();check(activeLookIndex===pausedLook,'Pause stops auto advance');",context);
const navOrder=[...html.match(/<nav class="bottom">([\s\S]*?)<\/nav>/)[1].matchAll(/navTo\('([^']+)'/g)].map(m=>m[1]);
if(navOrder.join(',')!=='home,discover,trendy,sports,cart')throw Error('Navigation order');
vm.runInContext("check(products.length===61,'New sports catalog');check(sizesFor(47).includes('M')&&sizesFor(48).includes('XL'),'Jersey sizes');selectSportsTab('creators');check($('sportsCreatorEdits').innerHTML.includes('Choose items & sizes'),'Creator edits');check(sportsProductIds('gear').every(id=>products.find(p=>p.id===id).c==='Cricket Gear'),'Gear filter');customizeSportsEdit(0);check(bundleDraft.items.some(p=>p.id===47),'Creator bundle');check(lensUrl(47).includes(encodeURIComponent(products.find(p=>p.id===47).sourceImg)),'Remote Lens source');",context);
vm.runInContext("selectSportsTab('creators');check(($('sportsCreatorEdits').innerHTML.match(/class=\\\"sports-edit-item\\\"/g)||[]).length===6,'All six creator items shown');check($('sportsCreatorEdits').innerHTML.includes('Blue India Fan Jersey')&&$('sportsCreatorEdits').innerHTML.includes('Denim Jeans')&&$('sportsCreatorEdits').innerHTML.includes('Aviator Sunglasses'),'Blue edit contents');",context);
vm.runInContext("setMenBudget(99);check(products.filter(p=>p.p<99).length>=4,'Under 99 catalog');check($('discoverBody').innerHTML.includes('Phone Stand'),'Budget feed');rememberViewed(33);menBudget=0;check(relatedToViewed().length>0,'View recommendations');check(relatedToViewed().every(p=>p.id!==33),'Exclude viewed product');setMenBudget(199);check(relatedToViewed().every(p=>p.p<199),'Recommendation budget');check(lensUrl(53).startsWith('https://lens.google.com/'),'Photo Lens URL');",context);
vm.runInContext("cart=[];customizeBundle('Date Night Ready',shopLooks[0].products,false);check(bundleDraft.dateLook,'Date look customization');check($('dateBundlePreview').innerHTML.includes('LIVE LOOK PREVIEW'),'Bundle color preview');bundleDraft.items[0].size='M';bundleDraft.items[1].size='32';bundleDraft.items[2].size='UK 8';chooseDateColor('bundle','shirt','Yellow');chooseDateColor('bundle','pants','Black');confirmBundle();check(cart.find(p=>p.id===33).color==='Yellow'&&cart.find(p=>p.id===46).color==='Black','Color saved');check(cart.every(p=>p.dateLookGroup),'Look group saved');renderCart();check($('cartBody').innerHTML.includes('Mix & match colors'),'Cart edit access');const group=cart[0].dateLookGroup;editDateCart(group);chooseDateColor('cart','shirt','Red');saveDateCartColors();check(cart.find(p=>p.id===33).color==='Red'&&cart.find(p=>p.id===33).size==='M','Edit preserves sizes');check(dateImage({shirt:'Red',pants:'Black'})==='assets/images/date-red-black.webp','Variant image');cart=[];pushCart(33,'M',null,'Red');pushCart(33,'M',null,'Yellow');check(cart.length===2,'Separate colors');",context);
console.log('PASS: syntax, sizes, cart edits, wishlist, bundle validation/pricing, return badges.');
try{console.log('Playwright: '+require.resolve('playwright'))}catch{console.log('Browser automation unavailable locally.')}
vm.runInContext("setMenBudget('gold');check(products.filter(p=>p.premium).length===4,'Gold catalog');check($('discoverBody').innerHTML.includes('Classic Dress Watch'),'Gold feed');check(!$('discoverBody').innerHTML.includes('Ankle Socks'),'Premium only');check(sizesFor(58).includes('M')&&sizesFor(60).includes('UK 8'),'Gold sizes');setMenBudget(0);check(!$('discoverBody').innerHTML.includes('men-gold'),'Gold hidden in All prices');check(!$('discoverBody').innerHTML.includes('Gold Edit'),'Premium products hidden');check(!$('menPriceTabs').innerHTML.includes('Under '+String.fromCharCode(8377)+'gold'),'Gold label');check($('menPriceTabs').innerHTML.includes('setMenBudget('+String.fromCharCode(39)+'gold'+String.fromCharCode(39)+')'),'Gold tab handler');setMenBudget(199);check(!$('discoverBody').innerHTML.includes('men-gold'),'Gold hidden in budget tabs');",context);

vm.runInContext("check(coinBalance()===12,'Starting balance');openEarnReview('older');$('earnRating').value='4';$('earnText').value='Good fit and comfortable';$('earnMedia').files=[];submitEarnReview();check(coinBalance()===12&&coinState.reviews.older,'Expired review has no points');openEarnReview('recent');$('earnRating').value='5';$('earnText').value='Comfortable shoes for everyday use';$('earnMedia').files=[];submitEarnReview();check(!coinState.reviews.recent,'Media required for points');$('earnMedia').files=[{type:'image/jpeg',name:'review.jpg'}];submitEarnReview();check(coinBalance()===22,'Review earning');submitEarnReview();check(coinBalance()===22,'No duplicate review earning');score=2;awardQuizPoints();check(coinBalance()===28&&coinState.quizPoints===8,'Quiz balance');awardQuizPoints();check(coinBalance()===28,'No duplicate quiz earning');renderCoins();check($('coinsBody').innerHTML.includes('28'),'Total shown');",context);
